/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjansterUtbildningRouteImport } from './routes/tjanster.utbildning'
import { Route as TjansterRekryteringRouteImport } from './routes/tjanster.rekrytering'
import { Route as TjansterChangeRouteImport } from './routes/tjanster.change'
import { Route as TjansterBemanningRouteImport } from './routes/tjanster.bemanning'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterUtbildningRoute = TjansterUtbildningRouteImport.update({
  id: '/tjanster/utbildning',
  path: '/tjanster/utbildning',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterRekryteringRoute = TjansterRekryteringRouteImport.update({
  id: '/tjanster/rekrytering',
  path: '/tjanster/rekrytering',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterChangeRoute = TjansterChangeRouteImport.update({
  id: '/tjanster/change',
  path: '/tjanster/change',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterBemanningRoute = TjansterBemanningRouteImport.update({
  id: '/tjanster/bemanning',
  path: '/tjanster/bemanning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/bemanning': typeof TjansterBemanningRoute
  '/tjanster/change': typeof TjansterChangeRoute
  '/tjanster/rekrytering': typeof TjansterRekryteringRoute
  '/tjanster/utbildning': typeof TjansterUtbildningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/bemanning': typeof TjansterBemanningRoute
  '/tjanster/change': typeof TjansterChangeRoute
  '/tjanster/rekrytering': typeof TjansterRekryteringRoute
  '/tjanster/utbildning': typeof TjansterUtbildningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tjanster/bemanning': typeof TjansterBemanningRoute
  '/tjanster/change': typeof TjansterChangeRoute
  '/tjanster/rekrytering': typeof TjansterRekryteringRoute
  '/tjanster/utbildning': typeof TjansterUtbildningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tjanster/bemanning'
    | '/tjanster/change'
    | '/tjanster/rekrytering'
    | '/tjanster/utbildning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tjanster/bemanning'
    | '/tjanster/change'
    | '/tjanster/rekrytering'
    | '/tjanster/utbildning'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tjanster/bemanning'
    | '/tjanster/change'
    | '/tjanster/rekrytering'
    | '/tjanster/utbildning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TjansterBemanningRoute: typeof TjansterBemanningRoute
  TjansterChangeRoute: typeof TjansterChangeRoute
  TjansterRekryteringRoute: typeof TjansterRekryteringRoute
  TjansterUtbildningRoute: typeof TjansterUtbildningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/utbildning': {
      id: '/tjanster/utbildning'
      path: '/tjanster/utbildning'
      fullPath: '/tjanster/utbildning'
      preLoaderRoute: typeof TjansterUtbildningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/rekrytering': {
      id: '/tjanster/rekrytering'
      path: '/tjanster/rekrytering'
      fullPath: '/tjanster/rekrytering'
      preLoaderRoute: typeof TjansterRekryteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/change': {
      id: '/tjanster/change'
      path: '/tjanster/change'
      fullPath: '/tjanster/change'
      preLoaderRoute: typeof TjansterChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/bemanning': {
      id: '/tjanster/bemanning'
      path: '/tjanster/bemanning'
      fullPath: '/tjanster/bemanning'
      preLoaderRoute: typeof TjansterBemanningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TjansterBemanningRoute: TjansterBemanningRoute,
  TjansterChangeRoute: TjansterChangeRoute,
  TjansterRekryteringRoute: TjansterRekryteringRoute,
  TjansterUtbildningRoute: TjansterUtbildningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
